steps:
  build-latest:
    image: woodpeckerci/plugin-docker-buildx
    platforms: linux/amd64
    settings:
      repo: ${CI_REPO/redpencilio/redpencil}
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push
