steps:
  build-feature:
    image: woodpeckerci/plugin-docker-buildx
    platforms: linux/amd64
    settings:
      repo: ${CI_REPO/redpencilio/redpencil}
      tags: ${CI_COMMIT_BRANCH/\//-}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [feature/*]
