steps:
  build-release:
    image: woodpeckerci/plugin-docker-buildx
    platforms: linux/amd64
    settings:
      repo: ${CI_REPO/redpencilio/redpencil}
      tags: "${CI_COMMIT_TAG##v}"
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  tag: v*
